app/urls.py
from django.urls import path
from . import views

app_name='app'

urlpatterns=[
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('works/', views.works, name='works '),
    path('message/', views.message, name='message'),
    path('contact/', views.contact, name="contact"),
    path('msgcheck/', views.msgcheck, name="msgcheck"),
]

project/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from app import urls as home

urlpatterns = [
    url('admin/', admin.site.urls),
    url('',include(home)),
]

app/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Messagemodels(models.Model):
    name = models.TextField(max_length=35)
    email = models.EmailField(max_length=254)
    message = models.TextField(max_length=140)
    date = models.DateField(default=timezone.now)

messageme/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms
from .models import Messagemodels

class Messageform(forms.Form):
    name = forms.CharField(label='Name', required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'type' : 'text', 'placeholder': 'required'}))
    email = forms.EmailField(label='Email', required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'required'}))
    message = forms.CharField(label='Message', required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'type' : 'text', 'placeholder': 'required'}))

app/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.db import IntegrityError
from .forms import Messageform
from .models import Messagemodels

# Create your views here.
response={}

def home(request):
    return render(request, 'home.html', response)

def about(request):
    return render(request, 'about.html', response)

def works(request):
    return render(request, 'works.html', response)

def msgcheck(request):
    return render(request, 'msgcheck.html', response)

def message(request):
    response['savemessage'] = Messageform
    table = Messagemodels.objects.all()
    response['table'] = table
    html = 'message.html'

    if(request.method == 'POST'):
        response['name'] = request.POST['name']
        response['email'] = request.POST['email']
        response['message'] = request.POST['message']
        try:
            writestat = Messagemodels(name=response['name'], email=response['email'], message=response['message'])
            writestat.save()
            status = 'valid'
            return JsonResponse({'stat':status})
        except IntegrityError as e:
            status = 'invalid'
            return JsonResponse({'stat':status})
    else:
        return render(request, 'message.html', response)

def contact(request):
    return render(request, 'contact.html', response)

messageme/views.py
from django.shortcuts import render

# Create your views here.

app/templates/about.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
    More about me
{% endblock title %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
{% endblock css %}

{% block content %}
        <div class="container">
            <div id="wrapper">
                <div id="section">
                    <h1 class="placing" style="text-align: center; justify-content: center;"> Educational background.</h1>
                        <div class="kotakan">
                            <p class="pls">SMAN 78 Jakarta, 2013-2017<p>
                            <p class="pls">Oakland Mills High School, 2015-2016<p>
                            <p class="pls">SMPN 134 Jakarta, 2010-2013<p>
                        </div>
                </div>

                <div id="section">
                    <h1 class="placing" style="text-align: center; justify-content: center;"> Experiences.</h1>
                        <div class="kotakan">
                            <p class="pls">PIC of Editorial Marketing, COMPFEST 11<p>
                            <p class="pls">Vice PIC of Liaison Officer, Wisuda Genap 2018<p>
                            <p class="pls">Data Entry Coordinator, Seleksi AFS 2018<p>
                        </div>
                </div>
            </div>
        </div>
        <script>
        $(document).ready(function() {
            $('#wrapper').fullpage();
        });
    </script>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
    Home
{% endblock title %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/fullpage.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/fullpage.js' %}"></script>
{% endblock css %}

{% block content %}
    <div class="container" id="black">
        <div id="wrapper">
            <div class="section">
                <h1>Puspacinantya, The 
                <span class = "txt-type" data-wait="2000" data-words='["Computer Science Undergrad.", "Avid Wanderer."]'></span>
                </h1>
                <h2>A very simple interface to know me more.</h2>
                <div class="downarrow"></div>
            </div>

            <div class="section" id="revelation">
                <div class="row">
                    <div class="col"><h1 style="text-align: center; justify-content: center;">This is her.</h1></div>
                </div>
                <div class="row">
                    <div class="col" style="justify-content: center;">
                         <img src="https://i.imgur.com/3niKvAk.jpg" class="rounded-circle mypic" style="width: 70%; height:auto; margin-left: 12.5%;">
                    </div>
                    <div class="col">
                        <img src="https://i.imgur.com/vXQGh9d.jpg?1" class="rounded-circle mypic" style="width: 70%; height:auto; margin-left: 12.5%;">
                    </div>
                    <div class="col">
                        <img src="https://i.imgur.com/PJLEytB.jpg" class="rounded-circle mypic"  style="width: 70%; height:auto; margin-left: 12.5%;">
                    </div>
                </div>
                <br>
                <div class="col" style="justify-content: center;">
                    <font size="3">Puspa is a third year student of Universitas Indonesia, pursuing
                    her study in the field of Information System. She has done many things in life,
                    and She is ready for more things to achieve!</font>
                    <br>
                    <font size="2">Her interest sparks on: tech 💻, writing ✍🏼, and reading 📚.</font>
                    <br>
                    <br>
                    <font size="3">Visit her on:</font>
                    <br>
                    <a href="https://www.linkedin.com/in/puspacinantya/" class="fa fa-linkedin"></a>
                    <a href="https://medium.com/@puspacinantya/" class="fa fa-medium"></a>
                    <a href="https://github.com/puspacntya/" class="fa fa-github"></a>
                    <a href="https://gitlab.com/puspacinantya/" class="fa fa-gitlab"></a>
                    <a href="https://www.instagram.com/puspacinantya/" class="fa fa-instagram"></a>
                    <a href="mailto:puspacinantya@gmail.com" class="fa fa-envelope"></a>
                </div>
            </div>
        </div>
        
    </div>

    <script>
        $(document).ready(function() {
            $('#wrapper').fullpage();
        });
    </script>
    
{% endblock %}

app/templates/message.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
    Message
{% endblock title %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
{% endblock css %}

{% block content %}
        <div class="container">
            <h1 style="text-align: center; justify-content: center; position: absolut;">Send your message.</h1>
            <div class="form-group">
            <div id="alertField">
                <form id="form" method="POST" action="{% url 'app:message' %}">
                    {% csrf_token %}
                    {{ savemessage }}
                    <br>
                    <br>
                    <div class="submit-btn">
                        <input id="submit" type="submit" class="btn btn-dangery" value="Submit">
                    </div>
                </form>
            </div>

            <br>
            <br>

            <a href="/msgcheck/" style="color:white;">Check out other messages HERE</a>

        </div>
     <script>
        $(document).ready(function() {
            $('#wrapper').fullpage();
        });
    </script>
    
{% endblock %}

app/templates/msgcheck.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
    All your messages
{% endblock title %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
{% endblock css %}

{% block content %}
        <div class="container">
            <h1 style="text-align: center; justify-content: center; position: absolut;">Your Messages.</h1>
            <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Sender Name</th>
                            <th>Message</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in table %}
                        <tr>
                            <td> {{i.name}} </td>
                            <td> {{i.message}} </td>
                        </tr>
                        {% endfor %}
                    </tbody>
            </table>

        </div>
{% endblock %}

app/templates/works.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
    More about me
{% endblock title %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
{% endblock css %}

{% block content %}
        <div class="container">
            <div id="wrapper">
                <div class="section"> 
                    <h1 class="placing" style="text-align: center; justify-content: center;"> My works.</h1>

                    <div class="row">
                        <div class="col-sm-6">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">Sinar Perak</h5>
                                    <h6 class="card-subtitle mb-2 text-muted">A website</h6>
                                    <p class="card-text">Similar to crowdfunding  website in which user can login through their google
                                    and pick what program they want to donate in.</p>
                                    <a href="https://demippw.herokuapp.com/" class="card-link">See the website</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">Writing Portfolio</h5>
                                    <h6 class="card-subtitle mb-2 text-muted">Writings</h6>
                                    <p class="card-text">A collection of my writings, mostly articles on COMPFEST and technologies.</p>
                                    <a href="https://www.clippings.me/puspacinantya" class="card-link">See the portfolio</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
        $(document).ready(function() {
            $('#wrapper').fullpage();
        });
    </script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Puspacinantya -
        {% block title %}

        {% endblock title %}
    </title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://i.imgur.com/njQ014H.png">
    {% block css %}
    
    {% endblock css %}
</head>
<body>
    <div class="container">
        <!-- <header>
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a class="nav-link" style="color: white;" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: white;" href="/about/">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="color: white;" href="/works/">Works</a>
            </li>
        </ul>
        </header> -->
        {% block content %}
        <!--Tulis content disini-->
        {% endblock %}
        <footer>
            <h6 style="text-align:center; color:grey;">Puspacinantya © 2020</h6>
        </footer>
    </div>   
</body>

</html>